apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: puchi

resources:
  - namespace.yaml
  - puchi-fe/deployment.yaml
  - puchi-fe/service.yaml
  - puchi-fe/ingress.yaml

commonLabels:
  app.kubernetes.io/name: puchi-fe
  app.kubernetes.io/part-of: puchi-frontend

configMapGenerator:
  - name: puchi-fe-config
    literals:
      - NEXT_PUBLIC_API_URL=https://puchi.io.vn
      - NODE_ENV=production

secretGenerator:
  - name: puchi-fe-secrets
    literals:
      - SOME_SECRET=production-secret
