apiVersion: v1
kind: ConfigMap
metadata:
  name: puchi-fe-config
  namespace: puchi
data:
  NEXT_PUBLIC_APP_URL: "https://puchi.io.vn/"
  NEXT_PUBLIC_API_URL: "https://api.puchi.io.vn/"
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: "/sign-in"
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: "/sign-up"
  NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL: "/learn"
  NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL: "/learn"
  NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: "/"
  NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: "/"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_live_Y2xlcmsucHVjaGkuaW8udm4k"
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: "cloudinaryhoan"
  ANALYZE: "false"
