apiVersion: apps/v1
kind: Deployment
metadata:
  name: puchi-fe
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: puchi-fe
          image: ghcr.io/puchidemy/puchi-frontend:dev
